spring.application.name=renteasy

# Active Profile
spring.profiles.active=prod

# JPA
spring.jpa.open-in-view=false

# JWT
jwt.secret-key=6q/OpcGxuHTC0XqhGsKa2yzsxgKN1lgPwRiiUXArUq4=
jwt.expiration-ms=3600000

# Internationalization
spring.messages.encoding=UTF-8

